name: release-workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8 for Release
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: adopt
      - name: Setup Unit Test
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Unit tests
          run: pytest
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2.5.4
        with:
          semantic_version: 17
          extra_plugins: |
            @semantic-release/git@9.0.1
            @semantic-release/exec@6.0.1
            @semantic-release/changelog@6.0.0
            @jortfal/semantic-release-terraform-config
          extends: |
            @jortfal/semantic-release-terraform-config
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}